### ISSUE TITLE
Command to copy entire content (without metadata) from a note.

### ISSUE THREAD

**Issue by LeslyeCream** [skztr/obsidian-plugin-section-copy#1]
I think it could be very useful. As far as I know there is no extension or native function to get it. Especially on Obsidian mobile. It's a pain to have to do an intermediate edit to copy my note, delete metadata and recopy it all.

**Comment by LeslyeCream** [comment]
Both options are a good but I think one than a command offers more possibilities. Use it next to Commander, shortcut and so on

**Comment by skztr** [comment]
try out the latest version 1.2.0, which addresses this

**Comment by LeslyeCream** [comment]
It works perfectly 💯 Thanks!

**Comment by LeslyeCream** [comment]
Sorry but... The action from the command palette no longer copies the contents of the note without its metadata. I've tried different settings without success.

**Comment by elementsuite-will** [comment]
> Sorry but... The action from the command palette no longer copies the contents of the note without its metadata. I've tried different settings without success. 

Can you please open a new issue mentioning this? I don't think there's a way to re-open an issue on GitHub, so a new issue would serve as a good reminder for me to look into this

Thank you

**Comment by skztr** [comment]
> Sorry but... The action from the command palette no longer copies the contents of the note without its metadata. I've tried different settings without success. 

Can you please reference this in a new issue? 
I don't think there's a way to re-open an existing issue, so a new issue would serve as a good reminder for me to look into this. 

Thank you
